project:
  type: website



website:
  # announcement: 
  #   icon: info-circle
  #   dismissable: true
  #   content: "**Alert** - this is some information that you should pay attention to"
  #   type: primary
  #   position: below-navbar

  site-url: http://0.0.0.0:4200/
  title: "Literature Reviews in Information Systems"
  navbar:
    left:
      - text: "Database"
        href: index.qmd
      - text: "Statistics"
        href: statistics.qmd
      - text: "About"
        href: about.qmd

      - icon: github
        href: https://github.com/digital-work-lab/literature-reviews-in-information-systems

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    code-fold: true
    smooth-scroll: true
    body-width: 800px

execute:
  freeze: auto

